// <auto-generated />
using System;
using BadReview.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BadReview.Api.Migrations
{
    [DbContext(typeof(BadReviewContext))]
    [Migration("20251124011819_ChangePostgresDateTimeColumnType")]
    partial class ChangePostgresDateTimeColumnType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BadReview.Api.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long?>("StartDate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("BadReview.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("Count_RatingBadReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long?>("Date")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<double>("RatingIGDB")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Summary")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<long>("Total_RatingBadReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Video")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Games", t =>
                        {
                            t.HasCheckConstraint("CK_Games_Count_RatingBadReview", "\"Count_RatingBadReview\" >= 0");

                            t.HasCheckConstraint("CK_Games_Total_RatingBadReview", "\"Total_RatingBadReview\" >= 0");
                        });
                });

            modelBuilder.Entity("BadReview.Api.Models.GameDeveloper", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "DeveloperId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("GameDevelopers");
                });

            modelBuilder.Entity("BadReview.Api.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("BadReview.Api.Models.GamePlatform", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("BadReview.Api.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("BadReview.Api.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Generation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("PlatformType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PlatformTypeName")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Summary")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("BadReview.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ReviewText")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StateEnum")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("UX_Reviews_UserId_GameId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Dates", "(\"StartDate\" IS NULL OR \"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\")");

                            t.HasCheckConstraint("CK_Reviews_Rating", "\"Rating\" >= 0 AND \"Rating\" <= 5");

                            t.HasCheckConstraint("CK_Reviews_ReviewFlags", "(\"IsReview\" = true OR \"IsFavorite\" = true)");

                            t.HasCheckConstraint("CK_Reviews_StateDates", "(\"StateEnum\" = 1 AND \"EndDate\" IS NULL) OR (\"StateEnum\" = 2 AND \"StartDate\" IS NULL AND \"EndDate\" IS NULL) OR (\"StateEnum\" IN (0,3))");
                        });
                });

            modelBuilder.Entity("BadReview.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FullName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Birthday_MinAge", "\"Birthday\" IS NULL OR EXTRACT(YEAR FROM AGE(CURRENT_TIMESTAMP, \"Birthday\")) >= 12");

                            t.HasCheckConstraint("CK_Users_Country", "\"Country\" >= 0");

                            t.HasCheckConstraint("CK_Users_Email_Format", "\"Email\" NOT LIKE '% %' AND \"Email\" LIKE '___%@__%._%' AND (LENGTH(\"Email\") - LENGTH(REPLACE(\"Email\", '@', ''))) = 1 AND \"Email\" ~ '^[a-zA-Z0-9@._-]+$'");

                            t.HasCheckConstraint("CK_Users_FullName_AlphaSpace", "\"FullName\" IS NULL OR \"FullName\" ~ '^[a-zA-Z ]+$'");

                            t.HasCheckConstraint("CK_Users_Username_ValidChars", "\"Username\" ~ '^[a-zA-Z0-9._-]+$'");
                        });
                });

            modelBuilder.Entity("BadReview.Api.Models.Developer", b =>
                {
                    b.OwnsOne("BadReview.Api.Models.Owned.Image", "Logo", b1 =>
                        {
                            b1.Property<int>("DeveloperId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ImageHeight")
                                .HasColumnType("integer");

                            b1.Property<string>("ImageId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int?>("ImageWidth")
                                .HasColumnType("integer");

                            b1.HasKey("DeveloperId");

                            b1.ToTable("Developers");

                            b1.WithOwner()
                                .HasForeignKey("DeveloperId");
                        });

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("BadReview.Api.Models.Game", b =>
                {
                    b.OwnsOne("BadReview.Api.Models.Owned.Image", "Cover", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ImageHeight")
                                .HasColumnType("integer");

                            b1.Property<string>("ImageId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int?>("ImageWidth")
                                .HasColumnType("integer");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("BadReview.Api.Models.GameDeveloper", b =>
                {
                    b.HasOne("BadReview.Api.Models.Developer", "Developer")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadReview.Api.Models.Game", "Game")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BadReview.Api.Models.GameGenre", b =>
                {
                    b.HasOne("BadReview.Api.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadReview.Api.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BadReview.Api.Models.GamePlatform", b =>
                {
                    b.HasOne("BadReview.Api.Models.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadReview.Api.Models.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("BadReview.Api.Models.Platform", b =>
                {
                    b.OwnsOne("BadReview.Api.Models.Owned.Image", "Logo", b1 =>
                        {
                            b1.Property<int>("PlatformId")
                                .HasColumnType("integer");

                            b1.Property<int?>("ImageHeight")
                                .HasColumnType("integer");

                            b1.Property<string>("ImageId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int?>("ImageWidth")
                                .HasColumnType("integer");

                            b1.HasKey("PlatformId");

                            b1.ToTable("Platforms");

                            b1.WithOwner()
                                .HasForeignKey("PlatformId");
                        });

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("BadReview.Api.Models.Review", b =>
                {
                    b.HasOne("BadReview.Api.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadReview.Api.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BadReview.Api.Models.Owned.CUDate", "Date", b1 =>
                        {
                            b1.Property<int>("ReviewId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("ReviewId");

                            b1.ToTable("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId");
                        });

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BadReview.Api.Models.User", b =>
                {
                    b.OwnsOne("BadReview.Api.Models.Owned.CUDate", "Date", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<DateTime>("UpdatedAt")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Date")
                        .IsRequired();
                });

            modelBuilder.Entity("BadReview.Api.Models.Developer", b =>
                {
                    b.Navigation("GameDevelopers");
                });

            modelBuilder.Entity("BadReview.Api.Models.Game", b =>
                {
                    b.Navigation("GameDevelopers");

                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BadReview.Api.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("BadReview.Api.Models.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("BadReview.Api.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
